# Site settings
title: Sheekyll
description: "Here comes the description of your website"
url: "http://jbleuzen.github.io/"
baseurl: "/sheekyll"

# Sheekyll settings
logoUrl: http://placehold.it/160
email: your-email@domain.com
homeArticle: 5
twitterUsername: jbleuzen

# Build settings
markdown: kramdown
permalink: none
